package com.cz.platform.enums;

public enum ChargerType {
	KIRANA_CHARZER_GSM, KIRANA_CHARZER_BLE, OTHER_NETWORK_CHARGER, KIRANA_CHARZER_FLEXTRON, CHARGE_MOD_BHARAT_AC,
	EV_POINT_CHARGER, KIRANA_CHARZER_FLEXTRON_WIFI, FLEXTRON_BLE_OMNI, MEKR_OMNI, MOKO_PLUG_OMNI, OCPP_16_JSON_CHARGER;

}
